const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image:'../images/p1.jpg',
            price: 120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Adidas Slim Shirt',
            category: 'Shirts',
            image:'../images/p2.jpg',
            price: 122,
            brand:'Adidas',
            rating: 4.1,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Roadster Slim Shirt',
            category: 'Shirts',
            image:'../images/p3.jpg',
            price: 120,
            brand:'Roadster',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nike Slim pants',
            category: 'Shirts',
            image:'../images/p4.jpg',
            price: 170,
            brand:'Nike',
            rating: 4.3,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Puma Slim Pant',
            category: 'Shirts',
            image:'../images/p5.jpg',
            price: 126,
            brand:'Puma',
            rating: 4.4,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Adidas Fit Pant',
            category: 'Pants',
            image:'../images/p6.jpg',
            price: 190,
            brand:'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
    ],
};
export default data;